services:
  # trading-bot-a:
  #   image: kraken-trading-ai-bot:0.1.5  # Use the pre-built image
  #   container_name: kraken-trading-ai-bot
  #   command: python main.py  # Replace with your app's entry point

  trading-bot-b:
    image: kraken-btc-trading-agent:1.0.0  # Replace with the correct image tag
    container_name: kraken-btc-trading-agent
    # depends_on:
    #   - trading-bot-a
    # entrypoint: ["sh", "-c", "sleep 180 && python main.py"]  # 3 minute delay (180 seconds)
    command: python main.py  # Replace with your app's entry point
