version: "3.9"

services:
  app:
    image: kraken-trading-bot:0.0.1  # Use the pre-built image
    container_name: kraken-trading-bot-container
    command: python main.py  # Replace with your app's entry point
