version: "3.9"

services:
  app:
    image: kraken-trading-ai-bot:0.1.0  # Use the pre-built image
    container_name: kraken-trading-ai-bot
    command: python main.py  # Replace with your app's entry point
